name: Build ImmortalWrt

on:
#  schedule:
#    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y git subversion build-essential libncurses5-dev zlib1g-dev gawk gettext unzip libssl-dev python3 python3-setuptools file wget zstd

    - name: Download ImmortalWrt ImageBuilder
      run: |
        # 下载最新的 ImmortalWrt ImageBuilder（针对 x86_64）
        wget https://downloads.immortalwrt.org/releases/24.10.2/targets/x86/64/immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64.tar.zst
        # 解压 .tar.zst 文件
        tar -I zstd -xf immortalwrt-imagebuilder-24.10.2-x86-64.Linux-x86_64.tar.zst
        cd immortalwrt-imagebuilder-24.10.2-x86-64  # 进入解压后的目录

    - name: Copy custom files
      run: |
        cd immortalwrt-imagebuilder-24.10.2-x86-64
        cp -r ../../files ./files/  # 复制 UCI 脚本等自定义文件

    - name: Build image
      run: |
        cd immortalwrt-imagebuilder-24.10.2-x86-64
        make image PROFILE="immortalwrt_x86-64-generic" PACKAGES="luci"  # 示例：添加 LuCI，调整 PROFILE

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-firmware
        path: immortalwrt-imagebuilder-24.10.2-x86-64/bin/targets/x86/64/*.img.gz  # 固件输出路径

    - name: Release if manual
      if: github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v2
      with:
        files: immortalwrt-imagebuilder-24.10.2-x86-64/bin/targets/x86/64/*.img.gz
        tag_name: latest-build-${{ github.run_number }}
        name: ImmortalWrt Custom Build
        body: "自动编译的 ImmortalWrt 固件，包含自定义 UCI 脚本。"
